// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UEPCJJ3B56tmgoctcAVOBVBoZb1r5bI',
    appId: '1:619184823706:web:dc8f15ac7f673098a96e23',
    messagingSenderId: '619184823706',
    projectId: 'famsyncapp-97',
    authDomain: 'famsyncapp-97.firebaseapp.com',
    storageBucket: 'famsyncapp-97.firebasestorage.app',
    measurementId: 'G-W06QZFHWFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fBu-btBKgRLLoPmzi5AD1kjZrKkeruM',
    appId: '1:619184823706:android:fd5e535347cc5198a96e23',
    messagingSenderId: '619184823706',
    projectId: 'famsyncapp-97',
    storageBucket: 'famsyncapp-97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3qQPTferYt48bRzugsoLt0c-kZR7c4Q',
    appId: '1:619184823706:ios:e5ca1588ab76d2f1a96e23',
    messagingSenderId: '619184823706',
    projectId: 'famsyncapp-97',
    storageBucket: 'famsyncapp-97.firebasestorage.app',
    iosBundleId: 'com.example.famSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO3qQPTferYt48bRzugsoLt0c-kZR7c4Q',
    appId: '1:619184823706:ios:e5ca1588ab76d2f1a96e23',
    messagingSenderId: '619184823706',
    projectId: 'famsyncapp-97',
    storageBucket: 'famsyncapp-97.firebasestorage.app',
    iosBundleId: 'com.example.famSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2UEPCJJ3B56tmgoctcAVOBVBoZb1r5bI',
    appId: '1:619184823706:web:fd68e2629ca0e4a3a96e23',
    messagingSenderId: '619184823706',
    projectId: 'famsyncapp-97',
    authDomain: 'famsyncapp-97.firebaseapp.com',
    storageBucket: 'famsyncapp-97.firebasestorage.app',
    measurementId: 'G-165LN246CM',
  );
}
